NO_VALID_AUTH_TYPE: str = 'no_valid_auth_type'
NO_VALID_COOKIE_SUB: str = 'no_valid_cookie_sub'
AUTHORIZATION_MISSING: str = 'authorization_missing'
AUTHORIZATION_INVALID: str = 'authorization_invalid'
TOKEN_EXPIRED: str = 'token_expired'
TOKEN_INVALID: str = 'token_invalid'
TOKEN_DECODE_FAILURE: str = 'token_decode_failure'
USER_NOT_FOUND: str = 'user_not_found'
